version: '3'

services:
  db:
    image: mariadb
    container_name: mariadb_container
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  api:
    build: .
    container_name: node_container
    restart: always
    volumes:
      - .:/usr/app
    ports:
      - 3001:3001
    depends_on:
      - db
